node {
    checkout scm
 
    docker.withRegistry('https://us.gcr.io', 'gcr:personal-1332') {

        stage('Create Docker Image') {
            dir('hugo-builder') {
                def Img = docker.build("personal-1332/hugo-builder:${env.BUILD_NUMBER}")
                Img.push()
                Img.push("latest")
            }
        }
    }
}
