#!/bin/sh
# name of this script: wav2mp3.sh
# wav to mp3
cd /audio
for i in *.mp3; do
 if [ -e "$i" ]; then
   file=`basename "$i" .mp3`
   #lame -h -b 192 "$i" "$file.mp3"
    avconv -i "$i" -acodec pcm_s16le -ac 1 -ar 16000 "$file.wav"
 fi
done
